clients:
    type: simple
    total_clients: 100
    per_round: 10

    do_test:
        false
    speed_simulation: true
    simulation_distribution:
        distribution: pareto
        alpha: 1
    sleep_simulation: true
    avg_training_time: 10
    random_seed: 1

server:
    address: 127.0.0.1
    port: 8000
    do_test: true
    random_seed: 1
    step_window: 2
    synchronous: false
    simulate_wall_time: true
    minimum_clients_aggregated: 10
    staleness_bound: 10
    penalty: 2
    exploration_factor: 0.9
    staleness_factor: 0.5
    exploration_decaying_factor: 0.98
    min_explore_factor: 0.3
    staleness_penalty_factor: 0.5
    checkpoint_path: results/pisces/test/checkpoint
    model_path: results/pisces/test/models

data:
    partition_size: 100
    sampler:  noniid
    random_seed: 1
    per_client_classes_size: 20
    anchor_classes: 6
    consistent_clients_size: 6
    keep_anchor_classes_size: 6
    client_quantity_concentration: 0.4
    min_partition_size: 50
    response_latency_distribution:
        args:
            a: 1.2
            max: 180
            min: 16
            seed: 1
        name: zipf
        seconds: 14400
    disable_clients: false

trainer:
    type: basic
    rounds: 10
    max_concurrency: 6
    target_accuracy: 1
    epochs: 1
    batch_size: 32
    optimizer: SGD
    model_name: pisces_model
    num_classes: 20

algorithm:
    type: fedavg

results:
    result_path: results/pisces/test
    types: round, accuracy, elapsed_time, round_time
    plot: round-accuracy, elapsed_time-accuracy
    cols: 1
    subprocess: 23016
    trial: 6

parameters:
    optimizer:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0
